environments:

 XPE_PERF:
  protocol: https
  xpeHost: xpe-perf.qa.xyleme.com
  lcmsInstance: qa-10580
  documentUrl: /qa-10580/preview/1c6be087-e0dc-4c02-97ba-5b31e4174bcf/(outputType:OnlineCourse,packageType:Static%20SCORM%201.2)/env/qa/page/index.html
