environments:

 XPE2:
  scheme: https
  host: xpe2.qa.xyleme.com
  lcmsLoginUrl: https://qa.xyleme.com:10580/user-manager/login.jsf
  lcmsHomeUrl: https://qa.xyleme.com:10580/user-manager/launch.jsf
  baseHost: https://qa.xyleme.com:10580
  documentUrl: /qa-10580/preview/c2f0538d-09a2-4713-8bdf-9043282eed31/e4eada43-e849-4f8b-ab8f-7da2f04bbe42/page/index.html
 XPE:
  scheme: https
  host: xpe.qa.xyleme.com
  lcmsLoginUrl: https://qa.xyleme.com:10580/user-manager/login.jsf
  lcmsHomeUrl: https://qa.xyleme.com:10580/user-manager/launch.jsf
  baseHost: https://qa.xyleme.com:10580
  documentUrl: /qa-10580/preview/c2f0538d-09a2-4713-8bdf-9043282eed31/e4eada43-e849-4f8b-ab8f-7da2f04bbe42/page/index.html
 XPE_PROD:
  scheme: https
  host: xpe.xyleme.com
  lcmsLoginUrl: https://qa.xyleme.com:13580/user-manager/login.jsf
  lcmsHomeUrl: https://qa.xyleme.com:13580/user-manager/launch.jsf
  baseHost: https://qa.xyleme.com:13580
  documentUrl: /qa-13580/preview/c2f0538d-09a2-4713-8bdf-9043282eed31/e66b4f26-4f98-4f3c-a842-63c63a4d7e44/page/index.html
 XPE_1_4:
  scheme: https
  host: xpe.qa.xyleme.com
  lcmsLoginUrl: https://qa.xyleme.com:13080/user-manager/login.jsf
  lcmsHomeUrl: https://qa.xyleme.com:13080/user-manager/launch.jsf
  baseHost: https://qa.xyleme.com:13080
  documentUrl: /qa-13080/preview/c2f0538d-09a2-4713-8bdf-9043282eed31/f740a8fc-7799-4e5e-9360-2df8a35e37a1/page/index.html
